name: Update File with Current Time

on:
  schedule:
    - cron: '32 18 * * *'   # 13:45 UTC
    - cron: '33 12 * * *'   # 12:33 UTC
    - cron: '45 10 * * *'   # 10:45 UTC
    - cron: '10 9 * * *'    # 09:10 UTC
    - cron: '50 22 * * *'   # 22:50 UTC
    
  workflow_dispatch:  # This allows the workflow to be triggered manually from GitHub UI if needed.

jobs:
  update-time-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update file with current time
        run: |
          # Get the current time in a desired format (UTC)
          current_time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          # Update the file (assuming the file is named 'time.txt')
          echo "Current Time: $current_time" > time.txt
          
          # Commit the change if there's a modification
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add time.txt
          git commit -m "Update"
          git push
